# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Aquaint' do

# Firebase Pods
# -------------
pod 'Firebase'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'

# Misc Pods
# -------------
pod 'SimpleAuth'
pod 'KLCPopup'
# Pod for phone kit parsing
# -------------
source 'https://github.com/CocoaPods/Specs.git'

# AWS Pods
# -------------
pod 'AWSCore'
pod 'AWSLambda'
pod 'AWSS3'
pod 'AWSCognito'
pod 'AWSDynamoDB'
pod 'AWSMobileAnalytics'
pod 'AWSEC2'
pod 'AWSSNS'
pod 'AWSCognitoIdentityProvider'
pod 'GoogleSignIn'


# EXCESS AWS Pods
# -------------
#pod 'AWSAutoScaling'
#pod 'AWSCloudWatch'
#pod 'AWSCognitoIdentityProvider'
#pod 'AWSElasticLoadBalancing'
#pod 'AWSIoT'
#pod 'AWSKinesis'
#pod 'AWSMachineLearning'
#pod 'AWSSES'
#pod 'AWSSimpleDB'
#pod 'AWSSNS'
#pod 'AWSSQS'

end

target 'AquaintTests' do

end

target 'AquaintUITests' do

end

