# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Aquaint' do

pod 'Firebase'

pod 'SimpleAuth'

end

target 'AquaintTests' do

end

target 'AquaintUITests' do

end

